site_name: Algorand Developer Docs

theme:
  name: material
  font: Lato
  palette:
    primary: "#000000"
    accent: "#5662DB"
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite
  - attr_list
  - toc:
      permalink: true
      baselevel: 2

plugins:
  - search
  - awesome-pages

repo_name: algorand/docs
repo_url: https://github.com/algorand/docs
edit_uri: edit/staging/docs/
